<?php

namespace Container4MyL7UM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeMissionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\DemandeMissionRepository' shared autowired service.
     *
     * @return \App\Repository\DemandeMissionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DemandeMissionRepository'] = new \App\Repository\DemandeMissionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
