<?php

namespace Container4MyL7UM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeMission2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yGmjiG4.App\Entity\DemandeMission' shared service.
     *
     * @return \App\Entity\DemandeMission
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yGmjiG4": it needs an instance of "App\\Entity\\DemandeMission" but this type has been excluded in "config/services.yaml".');
    }
}
