<?php

namespace Container4MyL7UM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissionfreelencerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WeuR7V2.App\Entity\Missionfreelencer' shared service.
     *
     * @return \App\Entity\Missionfreelencer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WeuR7V2": it needs an instance of "App\\Entity\\Missionfreelencer" but this type has been excluded in "config/services.yaml".');
    }
}
