security:
    # Configure password hashing (this uses auto which selects a secure algorithm)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Define your user provider, loading users from your database using the UUID field
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configure your firewalls – one for development and one main firewall for your application
    firewalls:
        # The dev firewall disables security for assets and debug routes
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for handling the user authentication flow
        main:
            lazy: true
            provider: app_user_provider
            # Enable form login authentication; this generates the login form and processing routes
            form_login:
                login_path: app_login         # Route to handle login form (app_login must be defined)
                check_path: app_login   
                username_parameter: email
                password_parameter: motdepasse     
                    # Route to handle form submission for login
                default_target_path: app_home # Default page after login (app_home route must be defined)
                enable_csrf: true             # Enable CSRF protection for the login form

            logout:
                path: app_logout             # Route to handle user logout (app_logout must be defined)
                # Optionally specify a target after logout
                # target: app_home

    # Access control rules allow you to restrict access to certain parts of your site
    access_control:
        # Uncomment and customize the rules below as needed
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Test environment configuration: reduce password hashing work factor to speed up tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4         # Lower bcrypt cost for tests
                time_cost: 3    # Lower Argon2 time cost for tests
                memory_cost: 10 # Lower Argon2 memory cost for tests
