<?php

namespace ContainerFbC0vUQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2s5xC_9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2s5xC.9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2s5xC.9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', '.errored.YrW5VAZ', NULL, 'Cannot determine controller argument for "App\\Controller\\CandidaturemissionController::listerToutesCandidatures()": the $security argument is type-hinted with the non-existent class or interface: "App\\Controller\\Security". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'security' => '?',
        ]);
    }
}
