<?php

namespace ContainerFbC0vUQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_YrW5VAZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.YrW5VAZ' shared service.
     *
     * @return \App\Controller\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CandidaturemissionController::listerToutesCandidatures()": the $security argument is type-hinted with the non-existent class or interface: "App\\Controller\\Security". Did you forget to add a use statement?');
    }
}
