<?php

namespace ContainerVKi2YqK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L00f_WYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l00f.WY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l00f.WY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rep' => ['privates', 'App\\Repository\\FreelancerRepository', 'getFreelancerRepositoryService', true],
        ], [
            'rep' => 'App\\Repository\\FreelancerRepository',
        ]);
    }
}
