<?php

namespace ContainerVKi2YqK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSzNpx7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tSzNpx7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tSzNpx7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ChercheurController::deletechercheur' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ChercheurController::index' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\ChercheurController::profile' => ['privates', '.service_locator.Dxx..HD', 'get_ServiceLocator_Dxx__HDService', true],
            'App\\Controller\\ChercheurController::updatechercheur' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\FreelancerController::index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\FreelancerController::profile' => ['privates', '.service_locator.l00f.WY', 'get_ServiceLocator_L00f_WYService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModerateurController::index' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\ModerateurController::profile' => ['privates', '.service_locator.rbx9oxX', 'get_ServiceLocator_Rbx9oxXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ChercheurController:deletechercheur' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ChercheurController:index' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\ChercheurController:profile' => ['privates', '.service_locator.Dxx..HD', 'get_ServiceLocator_Dxx__HDService', true],
            'App\\Controller\\ChercheurController:updatechercheur' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\FreelancerController:index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\FreelancerController:profile' => ['privates', '.service_locator.l00f.WY', 'get_ServiceLocator_L00f_WYService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModerateurController:index' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\ModerateurController:profile' => ['privates', '.service_locator.rbx9oxX', 'get_ServiceLocator_Rbx9oxXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ChercheurController::deletechercheur' => '?',
            'App\\Controller\\ChercheurController::index' => '?',
            'App\\Controller\\ChercheurController::profile' => '?',
            'App\\Controller\\ChercheurController::updatechercheur' => '?',
            'App\\Controller\\FreelancerController::index' => '?',
            'App\\Controller\\FreelancerController::profile' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ModerateurController::index' => '?',
            'App\\Controller\\ModerateurController::profile' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ChercheurController:deletechercheur' => '?',
            'App\\Controller\\ChercheurController:index' => '?',
            'App\\Controller\\ChercheurController:profile' => '?',
            'App\\Controller\\ChercheurController:updatechercheur' => '?',
            'App\\Controller\\FreelancerController:index' => '?',
            'App\\Controller\\FreelancerController:profile' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ModerateurController:index' => '?',
            'App\\Controller\\ModerateurController:profile' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
