<?php

namespace ContainerLlNDyM6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T9rrN8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t9rrN8_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t9rrN8_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CandidatureController::addcandidature' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\CandidatureController::deletecandidature' => ['privates', '.service_locator.5FQ7ubt', 'get_ServiceLocator_5FQ7ubtService', true],
            'App\\Controller\\CandidatureController::index' => ['privates', '.service_locator.ZXaK3cG', 'get_ServiceLocator_ZXaK3cGService', true],
            'App\\Controller\\CandidatureController::showcandidature' => ['privates', '.service_locator.ZXaK3cG', 'get_ServiceLocator_ZXaK3cGService', true],
            'App\\Controller\\CandidatureController::updatecandidature' => ['privates', '.service_locator.5FQ7ubt', 'get_ServiceLocator_5FQ7ubtService', true],
            'App\\Controller\\OffreController::index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController::postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController::recherche' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController::ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController::index' => ['privates', '.service_locator.ctTTze6', 'get_ServiceLocator_CtTTze6Service', true],
            'App\\Controller\\OffremodController::modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController::supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\TypecontratController::addtypecontrat' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\TypecontratController::deletetypecontrat' => ['privates', '.service_locator.q2iQt7w', 'get_ServiceLocator_Q2iQt7wService', true],
            'App\\Controller\\TypecontratController::index' => ['privates', '.service_locator.9oQ0dhj', 'get_ServiceLocator_9oQ0dhjService', true],
            'App\\Controller\\TypecontratController::showtypecontrat' => ['privates', '.service_locator.9oQ0dhj', 'get_ServiceLocator_9oQ0dhjService', true],
            'App\\Controller\\TypecontratController::updatetypecontrat' => ['privates', '.service_locator.q2iQt7w', 'get_ServiceLocator_Q2iQt7wService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CandidatureController:addcandidature' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\CandidatureController:deletecandidature' => ['privates', '.service_locator.5FQ7ubt', 'get_ServiceLocator_5FQ7ubtService', true],
            'App\\Controller\\CandidatureController:index' => ['privates', '.service_locator.ZXaK3cG', 'get_ServiceLocator_ZXaK3cGService', true],
            'App\\Controller\\CandidatureController:showcandidature' => ['privates', '.service_locator.ZXaK3cG', 'get_ServiceLocator_ZXaK3cGService', true],
            'App\\Controller\\CandidatureController:updatecandidature' => ['privates', '.service_locator.5FQ7ubt', 'get_ServiceLocator_5FQ7ubtService', true],
            'App\\Controller\\OffreController:index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController:postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController:recherche' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController:ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController:index' => ['privates', '.service_locator.ctTTze6', 'get_ServiceLocator_CtTTze6Service', true],
            'App\\Controller\\OffremodController:modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController:supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\TypecontratController:addtypecontrat' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\TypecontratController:deletetypecontrat' => ['privates', '.service_locator.q2iQt7w', 'get_ServiceLocator_Q2iQt7wService', true],
            'App\\Controller\\TypecontratController:index' => ['privates', '.service_locator.9oQ0dhj', 'get_ServiceLocator_9oQ0dhjService', true],
            'App\\Controller\\TypecontratController:showtypecontrat' => ['privates', '.service_locator.9oQ0dhj', 'get_ServiceLocator_9oQ0dhjService', true],
            'App\\Controller\\TypecontratController:updatetypecontrat' => ['privates', '.service_locator.q2iQt7w', 'get_ServiceLocator_Q2iQt7wService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CandidatureController::addcandidature' => '?',
            'App\\Controller\\CandidatureController::deletecandidature' => '?',
            'App\\Controller\\CandidatureController::index' => '?',
            'App\\Controller\\CandidatureController::showcandidature' => '?',
            'App\\Controller\\CandidatureController::updatecandidature' => '?',
            'App\\Controller\\OffreController::index' => '?',
            'App\\Controller\\OffreController::postuler' => '?',
            'App\\Controller\\OffreController::recherche' => '?',
            'App\\Controller\\OffremodController::ajoutoffre' => '?',
            'App\\Controller\\OffremodController::index' => '?',
            'App\\Controller\\OffremodController::modifoffre' => '?',
            'App\\Controller\\OffremodController::supprimeroffre' => '?',
            'App\\Controller\\TypecontratController::addtypecontrat' => '?',
            'App\\Controller\\TypecontratController::deletetypecontrat' => '?',
            'App\\Controller\\TypecontratController::index' => '?',
            'App\\Controller\\TypecontratController::showtypecontrat' => '?',
            'App\\Controller\\TypecontratController::updatetypecontrat' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CandidatureController:addcandidature' => '?',
            'App\\Controller\\CandidatureController:deletecandidature' => '?',
            'App\\Controller\\CandidatureController:index' => '?',
            'App\\Controller\\CandidatureController:showcandidature' => '?',
            'App\\Controller\\CandidatureController:updatecandidature' => '?',
            'App\\Controller\\OffreController:index' => '?',
            'App\\Controller\\OffreController:postuler' => '?',
            'App\\Controller\\OffreController:recherche' => '?',
            'App\\Controller\\OffremodController:ajoutoffre' => '?',
            'App\\Controller\\OffremodController:index' => '?',
            'App\\Controller\\OffremodController:modifoffre' => '?',
            'App\\Controller\\OffremodController:supprimeroffre' => '?',
            'App\\Controller\\TypecontratController:addtypecontrat' => '?',
            'App\\Controller\\TypecontratController:deletetypecontrat' => '?',
            'App\\Controller\\TypecontratController:index' => '?',
            'App\\Controller\\TypecontratController:showtypecontrat' => '?',
            'App\\Controller\\TypecontratController:updatetypecontrat' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
