<?php

namespace Container2UuRFcZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XZYRQlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xZYR_ql' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xZYR_ql'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EvenementsController::index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController::delete' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController::edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EventModController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventModController::show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'App\\Controller\\OffreController::index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController::postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController::ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController::index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffremodController::modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController::supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EvenementsController:index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController:delete' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController:edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EventModController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventModController:show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'App\\Controller\\OffreController:index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController:postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController:ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController:index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffremodController:modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController:supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EvenementsController::index' => '?',
            'App\\Controller\\EventModController::delete' => '?',
            'App\\Controller\\EventModController::edit' => '?',
            'App\\Controller\\EventModController::index' => '?',
            'App\\Controller\\EventModController::new' => '?',
            'App\\Controller\\EventModController::show' => '?',
            'App\\Controller\\OffreController::index' => '?',
            'App\\Controller\\OffreController::postuler' => '?',
            'App\\Controller\\OffremodController::ajoutoffre' => '?',
            'App\\Controller\\OffremodController::index' => '?',
            'App\\Controller\\OffremodController::modifoffre' => '?',
            'App\\Controller\\OffremodController::supprimeroffre' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementsController:index' => '?',
            'App\\Controller\\EventModController:delete' => '?',
            'App\\Controller\\EventModController:edit' => '?',
            'App\\Controller\\EventModController:index' => '?',
            'App\\Controller\\EventModController:new' => '?',
            'App\\Controller\\EventModController:show' => '?',
            'App\\Controller\\OffreController:index' => '?',
            'App\\Controller\\OffreController:postuler' => '?',
            'App\\Controller\\OffremodController:ajoutoffre' => '?',
            'App\\Controller\\OffremodController:index' => '?',
            'App\\Controller\\OffremodController:modifoffre' => '?',
            'App\\Controller\\OffremodController:supprimeroffre' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
