<?php

namespace ContainerDAZ1Qlv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateTimeImmutableListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\DateTimeImmutableListener' shared autowired service.
     *
     * @return \App\EventListener\DateTimeImmutableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventListener\\DateTimeImmutableListener'] = new \App\EventListener\DateTimeImmutableListener();
    }
}
