<?php

namespace ContainerTrcAEdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDompdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dompdf\Dompdf' shared autowired service.
     *
     * @return \Dompdf\Dompdf
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Dompdf\\Dompdf'] = new \Dompdf\Dompdf();
    }
}
