<?php

namespace ContainerTrcAEdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEvenementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Form\TypeEvenementType' shared autowired service.
     *
     * @return \App\Form\TypeEvenementType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Form\\TypeEvenementType'] = new \App\Form\TypeEvenementType();
    }
}
