<?php

namespace ContainerZITQF4S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FuhK8vsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fuhK8vs' shared service.
     *
     * @return \App\Controller\UserInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CandidaturemissionController::accepterOuRefuserCandidature()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserInterface". Did you forget to add a use statement?');
    }
}
