<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMlC0NKC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMlC0NKC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMlC0NKC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMlC0NKC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMlC0NKC\App_KernelProdContainer([
    'container.build_hash' => 'MlC0NKC',
    'container.build_id' => 'cb1462a8',
    'container.build_time' => 1739876237,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMlC0NKC');
