<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \App\Entity\Offre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'candidatures' => [parent::class, 'candidatures', null],
        "\0".parent::class."\0".'disponibilite' => [parent::class, 'disponibilite', null],
        "\0".parent::class."\0".'entreprise' => [parent::class, 'entreprise', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'localisation' => [parent::class, 'localisation', null],
        "\0".parent::class."\0".'nomposte' => [parent::class, 'nomposte', null],
        "\0".parent::class."\0".'salaire' => [parent::class, 'salaire', null],
        "\0".parent::class."\0".'typecontrat' => [parent::class, 'typecontrat', null],
        "\0".parent::class."\0".'typeoffre' => [parent::class, 'typeoffre', null],
        'candidatures' => [parent::class, 'candidatures', null],
        'disponibilite' => [parent::class, 'disponibilite', null],
        'entreprise' => [parent::class, 'entreprise', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'localisation' => [parent::class, 'localisation', null],
        'nomposte' => [parent::class, 'nomposte', null],
        'salaire' => [parent::class, 'salaire', null],
        'typecontrat' => [parent::class, 'typecontrat', null],
        'typeoffre' => [parent::class, 'typeoffre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
