<?php

namespace ContainerFXDByI7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LPVeEjhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lPVeEjh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lPVeEjh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ForumController::addDiscussion' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\ForumController::deleteDiscussion' => ['privates', '.service_locator.Bsv6qX0', 'get_ServiceLocator_Bsv6qX0Service', true],
            'App\\Controller\\ForumController::index' => ['privates', '.service_locator.aPy9iWU', 'get_ServiceLocator_APy9iWUService', true],
            'App\\Controller\\ForumController::updateformauthors' => ['privates', '.service_locator.dnSIpkt', 'get_ServiceLocator_DnSIpktService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ForumController:addDiscussion' => ['privates', '.service_locator.C5aMZSX', 'get_ServiceLocator_C5aMZSXService', true],
            'App\\Controller\\ForumController:deleteDiscussion' => ['privates', '.service_locator.Bsv6qX0', 'get_ServiceLocator_Bsv6qX0Service', true],
            'App\\Controller\\ForumController:index' => ['privates', '.service_locator.aPy9iWU', 'get_ServiceLocator_APy9iWUService', true],
            'App\\Controller\\ForumController:updateformauthors' => ['privates', '.service_locator.dnSIpkt', 'get_ServiceLocator_DnSIpktService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ForumController::addDiscussion' => '?',
            'App\\Controller\\ForumController::deleteDiscussion' => '?',
            'App\\Controller\\ForumController::index' => '?',
            'App\\Controller\\ForumController::updateformauthors' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ForumController:addDiscussion' => '?',
            'App\\Controller\\ForumController:deleteDiscussion' => '?',
            'App\\Controller\\ForumController:index' => '?',
            'App\\Controller\\ForumController:updateformauthors' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
