<?php

namespace ContainerMlC0NKC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EvenementsController::index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController::edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController::index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventModController::supprimeroffre' => ['privates', '.service_locator.YQbdD0B', 'get_ServiceLocator_YQbdD0BService', true],
            'App\\Controller\\EventTypeController::edit' => ['privates', '.service_locator.tKS5olJ', 'get_ServiceLocator_TKS5olJService', true],
            'App\\Controller\\EventTypeController::index' => ['privates', '.service_locator.BjTXOh2', 'get_ServiceLocator_BjTXOh2Service', true],
            'App\\Controller\\EventTypeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventTypeController::supprimeroffre' => ['privates', '.service_locator.RWLf6ZC', 'get_ServiceLocator_RWLf6ZCService', true],
            'App\\Controller\\OffreController::index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController::postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController::ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController::index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffremodController::modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController::supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EvenementsController:index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController:edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EventModController:index' => ['privates', '.service_locator.qP5LwVY', 'get_ServiceLocator_QP5LwVYService', true],
            'App\\Controller\\EventModController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventModController:supprimeroffre' => ['privates', '.service_locator.YQbdD0B', 'get_ServiceLocator_YQbdD0BService', true],
            'App\\Controller\\EventTypeController:edit' => ['privates', '.service_locator.tKS5olJ', 'get_ServiceLocator_TKS5olJService', true],
            'App\\Controller\\EventTypeController:index' => ['privates', '.service_locator.BjTXOh2', 'get_ServiceLocator_BjTXOh2Service', true],
            'App\\Controller\\EventTypeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventTypeController:supprimeroffre' => ['privates', '.service_locator.RWLf6ZC', 'get_ServiceLocator_RWLf6ZCService', true],
            'App\\Controller\\OffreController:index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffreController:postuler' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffremodController:ajoutoffre' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OffremodController:index' => ['privates', '.service_locator.IZCfKrU', 'get_ServiceLocator_IZCfKrUService', true],
            'App\\Controller\\OffremodController:modifoffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'App\\Controller\\OffremodController:supprimeroffre' => ['privates', '.service_locator.WaSJSkb', 'get_ServiceLocator_WaSJSkbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EvenementsController::index' => '?',
            'App\\Controller\\EventModController::edit' => '?',
            'App\\Controller\\EventModController::index' => '?',
            'App\\Controller\\EventModController::new' => '?',
            'App\\Controller\\EventModController::supprimeroffre' => '?',
            'App\\Controller\\EventTypeController::edit' => '?',
            'App\\Controller\\EventTypeController::index' => '?',
            'App\\Controller\\EventTypeController::new' => '?',
            'App\\Controller\\EventTypeController::supprimeroffre' => '?',
            'App\\Controller\\OffreController::index' => '?',
            'App\\Controller\\OffreController::postuler' => '?',
            'App\\Controller\\OffremodController::ajoutoffre' => '?',
            'App\\Controller\\OffremodController::index' => '?',
            'App\\Controller\\OffremodController::modifoffre' => '?',
            'App\\Controller\\OffremodController::supprimeroffre' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementsController:index' => '?',
            'App\\Controller\\EventModController:edit' => '?',
            'App\\Controller\\EventModController:index' => '?',
            'App\\Controller\\EventModController:new' => '?',
            'App\\Controller\\EventModController:supprimeroffre' => '?',
            'App\\Controller\\EventTypeController:edit' => '?',
            'App\\Controller\\EventTypeController:index' => '?',
            'App\\Controller\\EventTypeController:new' => '?',
            'App\\Controller\\EventTypeController:supprimeroffre' => '?',
            'App\\Controller\\OffreController:index' => '?',
            'App\\Controller\\OffreController:postuler' => '?',
            'App\\Controller\\OffremodController:ajoutoffre' => '?',
            'App\\Controller\\OffremodController:index' => '?',
            'App\\Controller\\OffremodController:modifoffre' => '?',
            'App\\Controller\\OffremodController:supprimeroffre' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
