<?php

<<<<<<<< HEAD:var/cache/dev/ContainerE2q9PZJ/getOffreControllerService.php
namespace ContainerE2q9PZJ;
========
namespace ContainerMlC0NKC;
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getEventTypeControllerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventTypeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EventTypeController' shared autowired service.
     *
     * @return \App\Controller\EventTypeController
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerE2q9PZJ/getOffreControllerService.php
        $container->services['App\\Controller\\OffreController'] = $instance = new \App\Controller\OffreController(($container->services['translator'] ?? self::getTranslatorService($container)));
========
        $container->services['App\\Controller\\EventTypeController'] = $instance = new \App\Controller\EventTypeController();
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getEventTypeControllerService.php

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EventTypeController', $container));

        return $instance;
    }
}
