<?php

<<<<<<<< HEAD:var/cache/dev/ContainerE2q9PZJ/getOffremodControllerService.php
namespace ContainerE2q9PZJ;
========
namespace ContainerMlC0NKC;
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getEventModControllerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventModControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EventModController' shared autowired service.
     *
     * @return \App\Controller\EventModController
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerE2q9PZJ/getOffremodControllerService.php
        $container->services['App\\Controller\\OffremodController'] = $instance = new \App\Controller\OffremodController(new \App\Repository\OffreRepository(), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
========
        $container->services['App\\Controller\\EventModController'] = $instance = new \App\Controller\EventModController();
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getEventModControllerService.php

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EventModController', $container));

        return $instance;
    }
}
