<?php

<<<<<<<< HEAD:var/cache/prod/ContainerMlC0NKC/getForm_RegistryService.php
<<<<<<<< HEAD:var/cache/dev/ContainerAf3Rx11/getForm_RegistryService.php
namespace ContainerAf3Rx11;
========
namespace ContainerMlC0NKC;
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getForm_RegistryService.php
========
namespace Container98L4R2C;
>>>>>>>> origin/MainTestWiem:var/cache/dev/Container98L4R2C/getForm_RegistryService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
<<<<<<<< HEAD:var/cache/dev/ContainerAf3Rx11/getForm_RegistryService.php
            'App\\Form\\CandidatureType' => ['privates', 'App\\Form\\CandidatureType', 'getCandidatureTypeService', true],
            'App\\Form\\CandidatureaddType' => ['privates', 'App\\Form\\CandidatureaddType', 'getCandidatureaddTypeService', true],
            'App\\Form\\ChangePasswordFormType' => ['privates', 'App\\Form\\ChangePasswordFormType', 'getChangePasswordFormTypeService', true],
            'App\\Form\\DemandeMissionType' => ['privates', 'App\\Form\\DemandeMissionType', 'getDemandeMissionTypeService', true],
            'App\\Form\\DiscussionType' => ['privates', 'App\\Form\\DiscussionType', 'getDiscussionTypeService', true],
            'App\\Form\\MessageType' => ['privates', 'App\\Form\\MessageType', 'getMessageTypeService', true],
            'App\\Form\\MissionfreelencerType' => ['privates', 'App\\Form\\MissionfreelencerType', 'getMissionfreelencerTypeService', true],
            'App\\Form\\OffreType' => ['privates', 'App\\Form\\OffreType', 'getOffreTypeService', true],
            'App\\Form\\RechercheoffreType' => ['privates', 'App\\Form\\RechercheoffreType', 'getRechercheoffreTypeService', true],
            'App\\Form\\ReplyType' => ['privates', 'App\\Form\\ReplyType', 'getReplyTypeService', true],
            'App\\Form\\ResetPasswordRequestFormType' => ['privates', 'App\\Form\\ResetPasswordRequestFormType', 'getResetPasswordRequestFormTypeService', true],
            'App\\Form\\TypeContratType' => ['privates', 'App\\Form\\TypeContratType', 'getTypeContratTypeService', true],
            'App\\Form\\TypeOffreType' => ['privates', 'App\\Form\\TypeOffreType', 'getTypeOffreTypeService', true],
========
            'App\\Form\\EventType' => ['privates', 'App\\Form\\EventType', 'getEventTypeService', true],
            'App\\Form\\OffreType' => ['privates', 'App\\Form\\OffreType', 'getOffreTypeService', true],
            'App\\Form\\TypeEvenementType' => ['privates', 'App\\Form\\TypeEvenementType', 'getTypeEvenementTypeService', true],
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getForm_RegistryService.php
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
<<<<<<<< HEAD:var/cache/dev/ContainerAf3Rx11/getForm_RegistryService.php
            'App\\Form\\CandidatureType' => '?',
            'App\\Form\\CandidatureaddType' => '?',
            'App\\Form\\ChangePasswordFormType' => '?',
            'App\\Form\\DemandeMissionType' => '?',
            'App\\Form\\DiscussionType' => '?',
            'App\\Form\\MessageType' => '?',
            'App\\Form\\MissionfreelencerType' => '?',
            'App\\Form\\OffreType' => '?',
            'App\\Form\\RechercheoffreType' => '?',
            'App\\Form\\ReplyType' => '?',
            'App\\Form\\ResetPasswordRequestFormType' => '?',
            'App\\Form\\TypeContratType' => '?',
            'App\\Form\\TypeOffreType' => '?',
========
            'App\\Form\\EventType' => '?',
            'App\\Form\\OffreType' => '?',
            'App\\Form\\TypeEvenementType' => '?',
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getForm_RegistryService.php
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
