<?php

<<<<<<<< HEAD:var/cache/dev/ContainerE2q9PZJ/getOffreTypeService.php
namespace ContainerE2q9PZJ;
========
namespace ContainerMlC0NKC;
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getOffreTypeService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffreTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\OffreType' shared autowired service.
     *
     * @return \App\Form\OffreType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\OffreType'] = new \App\Form\OffreType();
    }
}
