<?php

<<<<<<<< HEAD:var/cache/dev/ContainerY9ihsw7/getOffreRepositoryService.php
namespace ContainerY9ihsw7;
========
namespace ContainerMlC0NKC;
>>>>>>>> origin/HechBackUp:var/cache/prod/ContainerMlC0NKC/getOffreRepositoryService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffreRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OffreRepository' shared autowired service.
     *
     * @return \App\Repository\OffreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OffreRepository'] = new \App\Repository\OffreRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
