controllers:
    resource: '../src/Controller/'
    type: attribute
    # config/routes.yaml
app_profilechercheur:
    path: /profile/chercheur
    controller: App\Controller\ChercheurController::profile