# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  uploads_directory: "%kernel.project_dir%/public/uploads"
  images_directory: "%kernel.project_dir%/public/uploads/images"
  cv_directory: "%kernel.project_dir%/public/uploads/cvs"
  locale: 'fr'

services:
  # Default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Third-party services
  Dompdf\Dompdf: ~
  App\Entity\Offre:
    autowire: true
    autoconfigure: true
  App\Repository\OffreRepository:
    autowire: true
    autoconfigure: true
  App\Controller\OffremodController:
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Service\SmsService:
    arguments:
      $accountSid: '%env(TWILIO_ACCOUNT_SID)%' # Utilise la variable d'environnement TWILIO_ACCOUNT_SID
      $authToken: '%env(TWILIO_AUTH_TOKEN)%'    # Utilise la variable d'environnement TWILIO_AUTH_TOKEN
      $phoneNumber: '%env(TWILIO_PHONE_NUMBER)%' # Utilise la variable d'environnement TWILIO_PHONE_NUMBER