<?php

namespace ContainerV5jjXVX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidaturemissionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CiMjcjM.App\Entity\Candidaturemission' shared service.
     *
     * @return \App\Entity\Candidaturemission
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CiMjcjM": it needs an instance of "App\\Entity\\Candidaturemission" but this type has been excluded in "config/services.yaml".');
    }
}
