<?php

namespace ContainerV5jjXVX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissionfreelencerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MissionfreelencerType' shared autowired service.
     *
     * @return \App\Form\MissionfreelencerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MissionfreelencerType'] = new \App\Form\MissionfreelencerType();
    }
}
