<?php

namespace ContainerV5jjXVX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SmsService' shared autowired service.
     *
     * @return \App\Service\SmsService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SmsService'] = new \App\Service\SmsService($container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_PHONE_NUMBER'));
    }
}
