<?php

namespace Container43qSuC3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatureaddTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Form\CandidatureaddType' shared autowired service.
     *
     * @return \App\Form\CandidatureaddType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Form\\CandidatureaddType'] = new \App\Form\CandidatureaddType();
    }
}
