<?php

namespace Container43qSuC3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\NotificationRepository' shared autowired service.
     *
     * @return \App\Repository\NotificationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Repository\\NotificationRepository'] = new \App\Repository\NotificationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
