<?php

namespace Container43qSuC3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Offre' shared autowired service.
     *
     * @return \App\Entity\Offre
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Entity\\Offre'] = new \App\Entity\Offre();
    }
}
