<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CwrMxG4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CwrMxG4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CwrMxG4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'm' => ['services', 'doctrine', 'getDoctrineService', false],
            'rep' => ['privates', '.errored.vhIe34x', NULL, 'Cannot determine controller argument for "App\\Controller\\TypecontratController::updatetypecontrat()": the $rep argument is type-hinted with the non-existent class or interface: "App\\Repository\\TypeContratRepository".'],
        ], [
            'm' => '?',
            'rep' => '?',
        ]);
    }
}
