<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VopzpMkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vopzpMk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vopzpMk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offreRepository' => ['privates', '.errored.dvzBhv3', NULL, 'Cannot determine controller argument for "App\\Controller\\OffremodController::exportToPdf2()": the $offreRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\OffreRepository".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'offreRepository' => '?',
            'security' => '?',
        ]);
    }
}
