<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_N3pMJepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.n3pMJep' shared service.
     *
     * @return \App\Repository\OffreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\OffreController::index()": the $rep argument is type-hinted with the non-existent class or interface: "App\\Repository\\OffreRepository".');
    }
}
