<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DIe9KR1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dIe9KR1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dIe9KR1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offreRepository' => ['privates', '.errored.4unWBbS', NULL, 'Cannot determine controller argument for "App\\Controller\\OffremodController::index()": the $offreRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\OffreRepository".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'offreRepository' => '?',
            'security' => '?',
        ]);
    }
}
