<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PzDUuuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored._pzDUuu' shared service.
     *
     * @return \App\Repository\TypeOffreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TypeoffreController::deletetypeoffre()": the $rep argument is type-hinted with the non-existent class or interface: "App\\Repository\\TypeOffreRepository".');
    }
}
