<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VETIDBDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vETIDBD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vETIDBD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rep' => ['privates', '.errored.0xji9n2', NULL, 'Cannot determine controller argument for "App\\Controller\\TypecontratController::index()": the $rep argument is type-hinted with the non-existent class or interface: "App\\Repository\\TypeContratRepository".'],
        ], [
            'rep' => '?',
        ]);
    }
}
