<?php

namespace ContainerE2q9PZJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Pwa4XuLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Pwa4XuL' shared service.
     *
     * @return \App\Repository\TypeContratRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TypecontratController::showtypecontrat()": the $rep argument is type-hinted with the non-existent class or interface: "App\\Repository\\TypeContratRepository".');
    }
}
