<?php

namespace ContainerINadP0M;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpcW4EGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bpcW4EG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bpcW4EG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'm' => ['services', 'doctrine', 'getDoctrineService', false],
            'repDiscussion' => ['privates', 'App\\Repository\\DiscussionRepository', 'getDiscussionRepositoryService', true],
        ], [
            'm' => '?',
            'repDiscussion' => 'App\\Repository\\DiscussionRepository',
        ]);
    }
}
