<?php

namespace ContainerCP7fikI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XFolFv4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xFolFv4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xFolFv4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidatureRepo' => ['privates', 'App\\Repository\\CandidatureRepository', 'getCandidatureRepositoryService', true],
            'offreRepo' => ['privates', 'App\\Repository\\OffreRepository', 'getOffreRepositoryService', true],
        ], [
            'candidatureRepo' => 'App\\Repository\\CandidatureRepository',
            'offreRepo' => 'App\\Repository\\OffreRepository',
        ]);
    }
}
