<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY9ihsw7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY9ihsw7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY9ihsw7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY9ihsw7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY9ihsw7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y9ihsw7',
    'container.build_id' => '947e791b',
    'container.build_time' => 1740786695,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY9ihsw7');
