<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV5jjXVX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV5jjXVX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV5jjXVX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV5jjXVX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV5jjXVX\App_KernelDevDebugContainer([
    'container.build_hash' => 'V5jjXVX',
    'container.build_id' => '5e444d00',
    'container.build_time' => 1740995801,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV5jjXVX');
