<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLlNDyM6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLlNDyM6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLlNDyM6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLlNDyM6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLlNDyM6\App_KernelDevDebugContainer([
    'container.build_hash' => 'LlNDyM6',
    'container.build_id' => '3d1ce1fd',
    'container.build_time' => 1739660140,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLlNDyM6');
