<?php

namespace ContainerUMBBRHJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1OZdQwnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1OZdQwn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1OZdQwn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ChercheurController::index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\ChercheurController::profile' => ['privates', '.service_locator.WaDw3m4', 'get_ServiceLocator_WaDw3m4Service', true],
            'App\\Controller\\FreelancerController::index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\LoginController::forgotPassword' => ['privates', '.service_locator.pxIipq5', 'get_ServiceLocator_PxIipq5Service', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.qQMA5jQ', 'get_ServiceLocator_QQMA5jQService', true],
            'App\\Controller\\LoginController::resetPassword' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\ModerateurController::index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ChercheurController:index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\ChercheurController:profile' => ['privates', '.service_locator.WaDw3m4', 'get_ServiceLocator_WaDw3m4Service', true],
            'App\\Controller\\FreelancerController:index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'App\\Controller\\LoginController:forgotPassword' => ['privates', '.service_locator.pxIipq5', 'get_ServiceLocator_PxIipq5Service', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.qQMA5jQ', 'get_ServiceLocator_QQMA5jQService', true],
            'App\\Controller\\LoginController:resetPassword' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\ModerateurController:index' => ['privates', '.service_locator.eZK1Mwe', 'get_ServiceLocator_EZK1MweService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ChercheurController::index' => '?',
            'App\\Controller\\ChercheurController::profile' => '?',
            'App\\Controller\\FreelancerController::index' => '?',
            'App\\Controller\\LoginController::forgotPassword' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\LoginController::resetPassword' => '?',
            'App\\Controller\\ModerateurController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ChercheurController:index' => '?',
            'App\\Controller\\ChercheurController:profile' => '?',
            'App\\Controller\\FreelancerController:index' => '?',
            'App\\Controller\\LoginController:forgotPassword' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\LoginController:resetPassword' => '?',
            'App\\Controller\\ModerateurController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
